version: '3'
services:
  ui:
    build:
      context: ./ui
      args:
        FLOTILLA_API: http://localhost:3000/api/v1
        DEFAULT_CLUSTER: default
    environment:
      FLOTILLA_API: http://localhost:3000/api/v1
      DEFAULT_CLUSTER: default
    ports:
      - 5000:5000
      
  flotilla:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://flotilla:flotilla@db/flotilla?sslmode=disable
      READONLY_DATABASE_URL: postgresql://flotilla:flotilla@db/flotilla?sslmode=disable
      FLOTILLA_MODE: dev
      HTTP_SERVER_CORS_ALLOWED_ORIGINS: http://localhost:5000
      EKS_LOG_DRIVER_OPTIONS_S3_BUCKET_NAME: stitchfix.algo.eks.logs
      EKS_LOG_DRIVER_OPTIONS_S3_BUCKET_ROOT_DIR: logs
      EMR_JOB_QUEUE: flotilla-emr-staging
      EMR_JOB_STATUS_QUEUE: flotilla-eks-emr-staging-events
      EKS_JOB_QUEUE: flotilla-eks-staging
      EKS_EVENTS_QUEUE: flotilla-eks-infra-staging-events

    ports:
      - 3000:3000
  db:
    image: postgres
    environment:
      POSTGRES_USER: flotilla
      POSTGRES_DB: flotilla
      POSTGRES_PASSWORD: flotilla
    ports:
      - 5432:5432
