const API_ROOT = process.env.REACT_APP_FLOTILLA_API_ROOT || 'FILL_ME_IN'
const CLUSTERS_API_ROOT = process.env.REACT_APP_CLUSTERS_API_ROOT || 'FILL_ME_IN'
const IMAGE_ENDPOINT = process.env.REACT_APP_IMAGE_ENDPOINT || 'FILL_ME_IN'
const IMAGE_TAGS_ENDPOINT = process.env.REACT_APP_IMAGE_TAGS_ENDPOINT || 'FILL_ME_IN'
const DOCKER_REPOSITORY_HOST = process.env.REACT_APP_DOCKER_REPOSITORY_HOST || 'FILL_ME_IN'

export default {
  API_ROOT,
  CLUSTERS_API_ROOT,
  DOCKER_REPOSITORY_HOST,
  IMAGE_ENDPOINT,
  IMAGE_TAGS_ENDPOINT,
}
