const FLOTILLA_API = process.env.FLOTILLA_API || "FILL_ME_IN"
const CLUSTERS_API = process.env.CLUSTERS_API || "FILL_ME_IN"
const IMAGE_ENDPOINT = process.env.IMAGE_ENDPOINT || "FILL_ME_IN"
const IMAGE_TAGS_ENDPOINT = process.env.IMAGE_TAGS_ENDPOINT || "FILL_ME_IN"
const DOCKER_REPOSITORY_HOST =
  process.env.DOCKER_REPOSITORY_HOST || "FILL_ME_IN"
const DEFAULT_CLUSTER = process.env.DEFAULT_CLUSTER || "FILL_ME_IN"

export default {
  FLOTILLA_API,
  CLUSTERS_API,
  DOCKER_REPOSITORY_HOST,
  IMAGE_ENDPOINT,
  IMAGE_TAGS_ENDPOINT,
  DEFAULT_CLUSTER,
}
