export const REQUEST_DROPDOWN_OPTS = 'REQUEST_DROPDOWN_OPTS'
export const RECEIVE_DROPDOWN_OPTS = 'RECEIVE_DROPDOWN_OPTS'
export const RECEIVE_DROPDOWN_OPTS_ERROR = 'RECEIVE_DROPDOWN_OPTS_ERROR'
export const REQUEST_TASK = 'REQUEST_TASK'
export const RECEIVE_TASK = 'RECEIVE_TASK'
export const RECEIVE_TASK_ERROR = 'RECEIVE_TASK_ERROR'
export const RESET_TASK = 'RESET_TASK'

export const REQUEST_DELETE_TASK = 'REQUEST_DELETE_TASK'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR'

export const REQUEST_RUN_INFO = 'REQUEST_RUN_INFO'
export const RECEIVE_RUN_INFO = 'RECEIVE_RUN_INFO'
export const RECEIVE_RUN_INFO_ERROR = 'RECEIVE_RUN_INFO_ERROR'
export const REQUEST_RUN_LOGS = 'REQUEST_RUN_LOGS'
export const RECEIVE_RUN_LOGS = 'RECEIVE_RUN_LOGS'
export const RECEIVE_RUN_LOGS_ERROR = 'RECEIVE_RUN_LOGS_ERROR'
export const STOP_RUN_INTERVAL = 'STOP_RUN_INTERVAL'
export const RESET_RUN = 'RESET_RUN'

export const RECEIVE_LOCAL_RUN_CONFIG = 'RECEIVE_LOCAL_RUN_CONFIG'

export const UPDATE_RUN_FORM_QUERY = 'UPDATE_RUN_FORM_QUERY'

export const RENDER_MODAL = 'RENDER_MODAL'
export const UNRENDER_MODAL = 'UNRENDER_MODAL'
