export default {
  REQUEST_SELECT_OPTS: "REQUEST_SELECT_OPTS",
  RECEIVE_SELECT_OPTS: "RECEIVE_SELECT_OPTS",
  RECEIVE_SELECT_OPTS_ERROR: "RECEIVE_SELECT_OPTS_ERROR",
  RENDER_MODAL: "RENDER_MODAL",
  UNRENDER_MODAL: "UNRENDER_MODAL",
  RENDER_POPUP: "RENDER_POPUP",
  UNRENDER_POPUP: "UNRENDER_POPUP",
}
